@startsalt
title HomeScreen

{
  {* mplay | ... }
  ==
  {/ <b>Canciones</b> | Álbumes | Artistas | Playlists }
  ==
  {SI
    {#
      .  | <b>Título</b>       | Artista        | Dur.
      [>]| Bohemian Rhapsody   | Queen          | 5:55
      [>]| Hotel California    | Eagles         | 6:30
      [>]| Stairway to Heaven  | Led Zeppelin   | 8:02
      [>]| Comfortably Numb    | Pink Floyd     | 6:22
      [>]| November Rain       | Guns N' Roses  | 8:57
    }
  }
  ==
  {
    [<<] | [< ] | [  ▶  ] | [ >] | [>>]
    --
    <b>Bohemian Rhapsody</b> - Queen
    [============================]
  }
}

note right
  BLoC: MusicLibraryBloc, PlayerBloc
  Tap fila -> PlayerBloc.PlayTrack
  Tap tab -> cambia vista
end note
@endsalt
