@startsalt
title NowPlayingScreen

{
  {* < | <b>Now Playing</b> | ... }
  ==
  {
    .
    .
    [    Portada del Álbum (300x300)    ]
    .
    .
    <b>Bohemian Rhapsody</b>
    Queen  •  FLAC  •  320 kbps
    .
    [  ♥  ]  |  [  ⋮  ]
    --
    0:45 [===========              ] 5:55
    --
    [  ⇄  ] | [  <<  ] | [  ▶  ] | [  >>  ] | [  ↺  ]
    --
    Vol [==========               ] 100%
    --
    {/ <b>Letras</b> | Cola }
    --
    {SI
      Is this the real life?
      Is this just fantasy?
      <b>Caught in a landslide,</b>
      <b>No escape from reality.</b>
      Open your eyes,
    }
  }
}

note right
  BLoC: PlayerBloc, LyricsBloc
  Tap ▶/⏸ -> PlayerBloc.TogglePlay
  Drag slider -> PlayerBloc.Seek
  Tap ♥ -> LibraryBloc.ToggleFavorite
end note
@endsalt
