@startsalt
title AlbumDetailScreen

{
  {* < | <b>Álbum</b> | ... }
  ==
  {
    [  Portada (120x120)  ] | {
      <b>A Night at the Opera</b>
      Queen
      1975  •  12 canciones  •  48:02
      --
      [ ▶ Reproducir ] | [ ⇄ Aleatorio ]
    }
  }
  ==
  {SI
    {#
      # | <b>Título</b>       | Dur.
      1 | Death on Two Legs  | 3:44
      2 | Lazing on a Sunday | 1:08
      3 | I'm in Love with My Car | 3:04
      4 | You're My Best Friend | 2:52
      5 | '39                | 3:31
      6 | Bohemian Rhapsody  | 5:55
    }
  }
  ==
  {
    [<<] | [< ] | [  ▶  ] | [ >] | [>>]
    --
    <b>Bohemian Rhapsody</b> - Queen
  }
}

note right
  BLoC: AlbumBloc, PlayerBloc
  Tap fila -> PlayerBloc.PlayTrack
  Tap Reproducir -> PlayAlbum
  Tap Aleatorio -> ShuffleAlbum
end note
@endsalt
