@startsalt
title ArtistDetailScreen

{
  {* < | <b>Artista</b> | ... }
  ==
  {
    [  Foto (80x80)  ] | {
      <b>Queen</b>
      18 álbumes  •  204 canciones
      --
      [ ▶ Reproducir ] | [ ⇄ Aleatorio ]
    }
  }
  ==
  <b>Álbumes</b>
  {SI
    { [Portada\nA Night...] | [Portada\nJazz] | [Portada\nThe Game] | [Portada\nFlash G.] }
  }
  ==
  <b>Canciones populares</b>
  {SI
    {#
      . | <b>Título</b>       | Álbum         | Dur.
      [>]| Bohemian Rhapsody  | A Night...    | 5:55
      [>]| We Will Rock You   | News of...    | 2:01
      [>]| We Are the Champions | News of...  | 2:59
      [>]| Don't Stop Me Now  | Jazz          | 3:29
      [>]| Radio Ga Ga        | The Works     | 5:47
    }
  }
  ==
  {
    [<<] | [< ] | [  ▶  ] | [ >] | [>>]
    --
    <b>Bohemian Rhapsody</b> - Queen
  }
}

note right
  BLoC: ArtistBloc, PlayerBloc
  Tap álbum -> AlbumDetailScreen
  Tap canción -> PlayerBloc.PlayTrack
end note
@endsalt
