@startsalt
title PlaylistsScreen

{
  {* < | <b>Playlists</b> | ... }
  ==
  {SI
    {#
      . | <b>Nombre</b>       | Canciones
      [>]| Mis Favoritas      | 45 canciones
      [>]| Rock Clásico       | 23 canciones
      [>]| Para Trabajar      | 67 canciones
      [>]| Relax              | 18 canciones
    }
  }
  ==
  {
    [<<] | [< ] | [  ▶  ] | [ >] | [>>]
    --
    <b>Bohemian Rhapsody</b> - Queen
  }
}

note right
  BLoC: PlaylistBloc, PlayerBloc
  FAB (+) -> crear nueva playlist
  Tap fila -> PlaylistDetailScreen
  Long-press -> renombrar/eliminar
end note
@endsalt


@startsalt
title PlaylistDetailScreen

{
  {* < | <b>Rock Clásico</b> | [✎] | [🗑] }
  ==
  {
    <b>Rock Clásico</b>
    23 canciones  •  1h 42min
    [ ▶ Reproducir ] | [ ⇄ Aleatorio ]
  }
  ==
  {SI
    {#
      ≡ | # | <b>Título</b>      | Artista       | Dur.
      ≡ | 1 | Bohemian Rhapsody  | Queen         | 5:55
      ≡ | 2 | Hotel California   | Eagles        | 6:30
      ≡ | 3 | Stairway to Heaven | Led Zeppelin  | 8:02
      ≡ | 4 | Comfortably Numb   | Pink Floyd    | 6:22
    }
  }
  ==
  {
    [<<] | [< ] | [  ▶  ] | [ >] | [>>]
    --
    <b>Bohemian Rhapsody</b> - Queen
  }
}

note right
  BLoC: PlaylistBloc, PlayerBloc
  ≡ drag -> reordenar canciones
  Tap ✎ -> renombrar playlist
  Tap 🗑 -> eliminar playlist
end note
@endsalt
