@startsalt
title EqualizerScreen

{
  {* < | <b>Ecualizador</b> | ... }
  ==
  {
    Ecualizador activo | (X) ON | () OFF
  }
  --
  {
    Perfil: | ^Rock                      ^
  }
  ==
  {
    {
      <b>60Hz</b>
      +12
      .
      [  ]
      .
      .
      .
      .
      -12
    } | {
      <b>170Hz</b>
      +12
      .
      .
      [  ]
      .
      .
      .
      -12
    } | {
      <b>310Hz</b>
      +12
      .
      .
      .
      [  ]
      .
      .
      -12
    } | {
      <b>600Hz</b>
      +12
      .
      .
      .
      .
      [  ]
      .
      -12
    } | {
      <b>1kHz</b>
      +12
      .
      .
      .
      .
      .
      [  ]
      -12
    } | {
      <b>3kHz</b>
      +12
      .
      [  ]
      .
      .
      .
      .
      -12
    } | {
      <b>dB</b>
      +12
      +8
      +4
      0
      -4
      -8
      -12
    }
  }
  ==
  [ ↺  Restablecer ]
  ==
  {
    [<<] | [< ] | [  ▶  ] | [ >] | [>>]
    --
    <b>Bohemian Rhapsody</b> - Queen
  }
}

note right
  BLoC: EqualizerBloc, PlayerBloc
  Toggle ON/OFF -> EqualizerBloc.Toggle
  Drag banda -> EqualizerBloc.SetBand
  Dropdown -> EqualizerBloc.LoadPreset
  Restablecer -> EqualizerBloc.Reset
end note
@endsalt
