@startsalt
title SettingsScreen

{
  {* < | <b>Ajustes</b> | ... }
  ==
  {SI
    <b>Apariencia</b>
    --
    {
      Tema:
      (X) Seguir sistema | () Claro | () Oscuro
    }
    ==
    <b>Reproducción</b>
    --
    {
      Omitir silencios | [X] Activado
    }
    {
      Crossfade: | "  3 seg  "
    }
    {
      EQ predeterminado: | ^Rock                ^
    }
    ==
    <b>Idioma</b>
    --
    {
      Idioma: | ^Español (ES)          ^
    }
    ==
    <b>Datos</b>
    --
    [Copia de seguridad y restauración]
    ==
    <b>Acerca de</b>
    --
    mplay v1.0.0
    Flutter  •  Android
  }
  ==
  {
    [<<] | [< ] | [  ▶  ] | [ >] | [>>]
    --
    <b>Bohemian Rhapsody</b> - Queen
  }
}

note right
  BLoC: SettingsBloc, PlayerBloc
  Radio tema -> SettingsBloc.SetTheme
  Toggle -> SettingsBloc.SetSkipSilence
  Backup link -> BackupRestoreScreen
end note
@endsalt
